/**
 * SEEDER: 09_BuoiTapSeeder.js (Skipped 08 for brevity/autogenerated if needed)
 * Mục đích: Tạo buổi tập mẫu.
 */

module.exports = {
    up: async (queryInterface, Sequelize) => {
        const members = await queryInterface.sequelize.query(`SELECT TOP 5 id FROM nguoi_dungs WHERE email LIKE 'member%@test.com';`);
        const pts = await queryInterface.sequelize.query(`SELECT TOP 3 id FROM ho_so_pt;`);
        const branches = await queryInterface.sequelize.query(`SELECT TOP 1 id FROM chi_nhanhs;`);

        if (members[0].length === 0 || pts[0].length === 0 || branches[0].length === 0) return;

        const sessions = [];
        members[0].forEach((m, i) => {
            sessions.push({
                id_thanh_vien: m.id,
                id_pt: pts[0][i % pts[0].length].id,
                id_chi_nhanh: branches[0][0].id,
                thoi_gian_bat_dau: new Date(),
                thoi_gian_ket_thuc: new Date(new Date().getTime() + 60 * 60 * 1000), // +1h
                trang_thai: 'confirmed',
                ghi_chu: 'Khởi động kỹ',
                ngay_tao: new Date()
            });
        });

        await queryInterface.bulkInsert('buoi_taps', sessions, {});
    },

    down: async (queryInterface, Sequelize) => {
        await queryInterface.bulkDelete('buoi_taps', null, {});
    }
};
